version: '3.8'
services:
  mongodb:
    build:
      context: .
      dockerfile: Dockerfile.mongodb
    container_name: tetris-mongodb
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: tetris
      MONGO_INITDB_ROOT_PASSWORD: tetrispass
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data:
