import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Tetris",
  description: "Generated by Gen-e2",
  viewport: {
    width: "device-width",
    initialScale: 1,
    maximumScale: 1,
    userScalable: false,
    viewportFit: "cover",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html 
      lang="en" 
      className="overflow-hidden h-full w-full"
      style={{ 
        position: 'fixed', 
        height: '100%', 
        width: '100%',
        overflow: 'hidden',
        overscrollBehavior: 'none',
        touchAction: 'manipulation',
      } as React.CSSProperties}
    >
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased overflow-hidden h-full w-full game-container`}
        style={{
          position: 'fixed',
          top: 0,
          left: 0,
          height: '100vh',
          width: '100vw',
          overflow: 'hidden',
          overscrollBehavior: 'none',
          touchAction: 'manipulation',
        } as React.CSSProperties}
      >
        <div 
          className="game-container"
          style={{
            height: '100vh',
            width: '100vw',
            overflow: 'hidden',
            position: 'relative'
          }}
        >
          {children}
        </div>
      </body>
    </html>
  );
}
